Do not automatically pull binaries during the "branch" command
full-build/full-build pull request #191
Opened 2017-08-21 08:59 UTC by sergii-s

#168

2017-08-21 09:02 UTC, pchalamet commented
:white_check_mark: [Build full-build 4.2.24 completed](https://ci.appveyor.com/project/full-build/full-build-shu78/build/4.2.24) (commit https://github.com/full-build/full-build/commit/a9582aab87 by @sergii-s)

2017-08-24 08:48 UTC, pchalamet commented
PR #186 must be tested first - this is related because when you branch, you also want to get matching source code (and get broken .anthology). This shall solve this problem.

I also suspect there is maybe another bug related to the way bin/.anthology is used. It shall never be used as is but as the foundation on which all other available repo/.anthology are applied on. It's shall be the case but something might be broken there.

2017-08-24 08:52 UTC, sergii-s commented
If I want to build ALL from zero I dont want nor old binairies nor old anthology.

2017-08-24 08:54 UTC, pchalamet commented
Agree. But until you clone all sources you have *no* way to know you will end up building everything or not.

2017-08-24 08:55 UTC, pchalamet commented
if the idea is to build from scratch - implementing clean binaries instead would be more helpful ?

2017-08-24 12:40 UTC, sergii-s commented
> Agree. But until you clone all sources you have no way to know you will end up building everything or not.

Yes, but still no need of the old build result. Just need to pull + branch master repo and then all others.

> implementing clean binaries instead would be more helpful ?

I don't think so. There are another related problems, for example build sources when last build is corrupted (result missing but master repo is tagged). The only way to do with actual solution is to mock last build result or another manual action, but the main goal is build all from sources

2017-08-28 10:23 UTC, pchalamet requested changes

2017-08-28 10:23 UTC, pchalamet commented on src/FullBuild/CLI/CommandLine.fs
> +    | Token Token.Branch :: cmdArgs -> cmdArgs |> commandBranch false
Would prefer true to try first.

2017-08-28 12:15 UTC, pchalamet commented
:white_check_mark: [Build full-build 4.2.26 completed](https://ci.appveyor.com/project/full-build/full-build-shu78/build/4.2.26) (commit https://github.com/full-build/full-build/commit/5503655be3 by @sergii-s)

2017-08-28 14:00 UTC, pchalamet approved these changes

2017-08-28 14:19 UTC, merged